#!/usr/bin/env bash

git pull
python3 ./setup.py
#docker build --build-arg sha1=$SHA1 -t aishack .
#pid=`docker ps | grep 8000 | awk '{print$1}'`
#docker stop $pid
source /work/aishack/env_prod/bin/activate
source /work/aishack/configure.sh
supervisorctl restart aishack:uwsgi
