#!/usr/bin/env bash

git pull
python3 ./setup.py
source /work/aishack/env_prod/bin/activate
pip install -r requirements.txt
python3 /work/aishack/manage.py schedule_update
supervisorctl restart aishack:uwsgi
