#!/bin/sh

# Taken from http://forums.mysql.com/read.php?145,68269,92627
cat wp_users.sql wp_terms.sql wp_posts.sql | grep -v ' KEY "' | grep -v ' UNIQUE KEY "' | perl -e 'local $/;$_=<>;s/,\n\)/\n\)/gs;print "begin;\n";print;print "commit;\n"' | perl -pe ' if (/^(INSERT.+?)\(/) { $a=$1; s/\\'\''/'\'\''/g; s/\\n/\n/g; s/\),\(/\);\n$a\(/g; } ' | sqlite3 output.db
